<?php require_once("math.php");?>
<?php
//Random Dragons
//dragon name
$nameD00 = [
  "Zornaar",
  "Vyuprax",
  "Orlaturim",
  "Arqull",
  "Vorroth",
  "Brensashi",
  "Udolasar",
  "Otinaar",
  "Qelprax",
  "Balgrax",
  "Lumiroth",
  "Udodaar",
  "Hirakas",
  "Sulrakas",
  "Himash",
  "Shahazar",
  "Worzire",
  "Calujurn",
  "Morziros",
  "Vornaar",
  ];
   $name = Roller($nameD00);
//d100 Age: The dragon is...
$ageD00 = [
  "a wyrmling",
  "a wyrmling",
  "a youngling",
  "a youngling",
  "an adult",
  "an adult",
  "an ancient",
  "an ancient",
  " "
  ];
   $age = Roller($ageD00);
  if ($age == " ") {
    $ageD0 = [
    "a wyrmling",
    "a wyrmling",
    "a youngling",
    "a youngling",
    "an adult",
    "an adult",
    "an ancient one",
    "an ancient one",
    "a legendary"
    ];
    $age = Roller($ageD0);
  }
  $age .= "";
//d100 Color: The dragon is colored...
$colorD00 = [
  "black dragon, a sadistic beast fond of torture",
  "blue dragon, as proud as it is deadly",
  "green dragon, treacherously cunning",
  "red dragon, fiery and mad",
  "white dragon, a primal beast of ice",
  "brass dragon, always fond of a nice chat",
  "copper dragon, a crafty jokester",
  "gold dragon, majestic and wealthy",
  "silver dragon, friendly and caring",
  "bronze dragon, a dragon of the coast"
  ];
  $color = Roller($colorD00);
//d100 Major feature: The dragon has a unique appearance...
$featureMT00 = [
  "very sleek and soft scales that blend together and shine",
  "very sleek and soft scales that blend together and shine",
  "normal featurs for its color",
  "very tough and overgrown scales like barbaric plate armor",
  "shards of bone grow out of its body painfully at every angle",
  "shards of bone grow out of its body painfully at every angle",
  "crystal grows out of its scales seemingly brimming with magical power",
  "crystal grows out of its scales seemingly brimming with magical power",
  "runes carved into every scale each one with magical meaning",
  "albino skin and is often mistaken for a white dragon even though it may be of a different type",
  "albino skin and is often mistaken for a white dragon even though it may be of a different type",
  "its entire body is covered in thick shaggy fur",
  "multiple sets of small sharp wings",
  "its wings are coated in feathers giving it an oddly angelic appearance",
  "its wings are coated in feathers giving it an oddly angelic appearance",
  "an aura that radiates its chosen element making it glow with power under its scales",
  "weapons of all kinds lodged in its scales which the dragon wears proudly",
  "weapons of all kinds lodged in its scales which the dragon wears proudly",
  "thick chains. Most likely result of it losing a fight long ago",
  "thick chains. Most likely result of it losing a fight long ago",
  "large scars cut into its body",
  "large scars cut into its body",
  "shadows that seem to cling to its form like a cloak, no matter how bright the area is",
  "shadows that seem to cling to its form like a cloak, no matter how bright the area is",
  "a long slender body like a great serpent",
  "a long slender body like a great serpent",
  "an extra set of arms with strong muscle and sharp claws",
  "mottled scale coloring gives it a patchy look between two colors",
  "mottled scale coloring gives it a patchy look between two colors",
  "an exceedingly large with a bloated and obese body",
  "an exceedingly large with a bloated and obese body",
  "an insect-like mandible instead of a normal maw",
  "trouble shutting its over-large mouth with rows and rows of sharp teeth",
  "trouble shutting its over-large mouth with rows and rows of sharp teeth",
  "a slimy goo-like substance all over its body",
  "scales that appears to be changing colors at all times like an optical illusion",
  "bark all over its body",
  "stone all over its body",
  "multiple sets of eyes that glow with arcane power",
  "a large ancient gauntlet-like constructs on its claws that it uses in combat",
  "extra armor added to its body made out of adamantine",
  "extra armor added to its body made out of mithral",
  "a thin almost skeletal form",
  "a thin almost skeletal form",
  "an ugly diseased marks on its scales and a sickly pallor",
  "an ugly diseased marks on its scales and a sickly pallor",
  "its front legs are its wings in a way similar to a wyvern",
  "its front legs are its wings in a way similar to a wyvern",
  "grisly trophies of its kills on its body, covering it in severed heads and hands",
  "grisly trophies of its kills on its body, covering it in severed heads and hands",
  "areas of its body are completely devoid of scales.-Its skin has grown tough and leathery to make up for that",
  "areas of its body are completely devoid of scales.-Its skin has grown tough and leathery to make up for that",
  "fish-like adaptations to living at deep sea",
  "some kind of weakness and wears an exo-suit-like harness over its body to make it stronger",
  "a second head on its tail that can also shoot its breath weapon",
  "two heads, both with different personalities like an ettin",
  "an aura of its elemental power around it at all times, such as a bubble of uncontrollably burning flame",
  "an aura of its elemental power around it at all times, such as a bubble of uncontrollably burning flame",
  "no mouth and speaks entirely telepathically.-Its breath weapon is magical instead",
  "white eyes that are almost blind, and relies on its extremely strong smell and sound to find prey",
  "white eyes that are almost blind, and relies on its extremely strong smell and sound to find prey",
  "sharp monstrous barbs all over its body",
  "sharp monstrous barbs all over its body",
  "a very soft underbelly of a different color that is weaker than its other scales",
  "a very soft underbelly of a different color that is weaker than its other scales",
  "gemstones and coins inset into its scales like a traditional dragon, reinforcing its strength and armor",
  "gemstones and coins inset into its scales like a traditional dragon, reinforcing its strength and armor",
  "sharp scythe-like claws on its forelegs",
  "sharp scythe-like claws on its forelegs",
  "its claws are very long and slender, but it has great tactile control of them",
  "its claws are very long and slender, but it has great tactile control of them",
  "a very long tongue that it eagerly uses like an extra arm",
  "a face eerily similar to a humanoid’s",
  "a form  that is slightly more humanoid than usual, with the typical muscles more prominent and obvious than usual",
  "ridges of horn-like spines over its back, each one like a sharp blade",
  "ridges of horn-like spines over its back, each one like a sharp blade",
  "very long curled horns like a minotaur that it will to head-butt and gore foes",
  "very long curled horns like a minotaur that it will to head-butt and gore foes",
  "only one, very long horn like a unicorn",
  "only one, very long horn like a unicorn",
  "paw that seems to have no claws at all instead relying on hard slamming attacks",
  "an empty space where an entire limb used to be",
  "half of its face missing, revealing the bone and muscle beneath",
  "its scales are slightly translucent allowing one to see its insides",
  "a cobra-like hood on its neck",
  "a cobra-like hood on its neck",
  "bandages and wrappings around a good deal of its body",
  "a somewhat bird-like beak instead of a traditional dragon maw",
  "eerily human-like hands instead of claws",
  "a disturbing number of multiple scuttling legs",
  "huge crab-like claws",
  "a beholder-like eye with several twisting eyestalks",
  "a huge twisting worm-like body",
  "a sharp bladed tail that it uses as a slashing weapon",
  "a bloody stump where its tail used to be",
  "a cloud of smoke around its body at all times",
  "huge and actually somewhat uncomfortable wings that sweep around it",
  "a pose where it stands on its hind legs similar to a humanoid",
  "carefully manicured claws in sword-like shapes",
  "broad fan-like tail fins",
  "wreathes of flowers and plants around its body"
  ];
  $mayor = Roller($featureMT00);
   if ($age == "a legendary") {
     $mayor .= " and ".(Roller($featureMT00));
   }
   $mayor .= "";
//d100 Minor feature: The dragon also has...
$featuremT00 = [
  "one horn missing; it was broken off",
  "one horn missing; it was broken off",
  "one horn missing; it was broken off",
  "light scarring around the eyes",
  "light scarring around the eyes",
  "a heavy mace-like tail which it will happily use as a weapon",
  "a heavy mace-like tail which it will happily use as a weapon",
  "a heavy mace-like tail which it will happily use as a weapon",
  "a mane of ‘hair’ by its head",
  "a mane of ‘hair’ by its head",
  "a crown of horns around the top of its skull",
  "a crown of horns around the top of its skull",
  "a crown of horns around the top of its skull",
  "a face that looks like a skull",
  "a face that looks like a skull",
  "a face that looks like a skull",
  "a pair of overly large fangs",
  "a pair of overly large fangs",
  "a pair of overly large fangs",
  "a pair of overly large fangs",
  "a powerful artifact of some kind embedded in its forehead",
  "a powerful artifact of some kind embedded in its forehead",
  "an extra tail",
  "an extra tail",
  "each eye is a different color and extra vibrant",
  "each eye is a different color and extra vibrant",
  "each eye is a different color and extra vibrant",
  "a hungry and yet charming grin",
  "a hungry and yet charming grin",
  "a hungry and yet charming grin",
  "a beard of hanging scales",
  "a beard of hanging scales",
  "a beard of hanging scales",
  "scales of varying shininess and hue",
  "scales of varying shininess and hue",
  "scales of varying shininess and hue",
  "far brighter colors than normal",
  "far brighter colors than normal",
  "far darker colors than normal",
  "far darker colors than normal",
  "mud or dirt covering its scales",
  "mud or dirt covering its scales",
  "mud or dirt covering its scales",
  "some kind of make up on its face",
  "some kind of make up on its face",
  "painted tattoos on its scales",
  "painted tattoos on its scales",
  "several missing teeth",
  "several missing teeth",
  "several missing teeth",
  "a single missing scale making a small weak point",
  "a single missing scale making a small weak point",
  "a single missing scale making a small weak point",
  "a missing wing",
  "a missing wing",
  "a missing wing",
  "stripe-like patterns to its scales",
  "stripe-like patterns to its scales",
  "stripe-like patterns to its scales",
  "one single magical eye",
  "one single magical eye",
  "a pet that constantly stays by its side",
  "a pet that constantly stays by its side",
  "brand-like markings burnt onto its body",
  "brand-like markings burnt onto its body",
  "smoke constantly billowing from its mouth and nostrils",
  "smoke constantly billowing from its mouth and nostrils",
  "smoke constantly billowing from its mouth and nostrils",
  "a thin slender form",
  "a thin slender form",
  "a thin slender form",
  "a cuddly stocky form",
  "a cuddly stocky form",
  "a spiny ridge on its back",
  "a spiny ridge on its back",
  "a spiny ridge on its back",
  "very large custom-made eyeglasses",
  "very large custom-made eyeglasses",
  "a large ridge behind its head like a triceratops",
  "a large ridge behind its head like a triceratops",
  "a large ridge behind its head like a triceratops",
  "shackles on its legs",
  "shackles on its legs",
  "shackles on its legs",
  "plants growing on its body",
  "plants growing on its body",
  "a very long tail, several times the length of its body",
  "a very long tail, several times the length of its body",
  "large fins on its tail",
  "large fins on its tail",
  "a vastly different than normal hue",
  "a vastly different than normal hue",
  "fins on its limbs",
  "fins on its limbs",
  "a large overbiting jaw",
  "a large overbiting jaw",
  "a large underbiting jaw",
  "a large underbiting jaw",
  "fake horns",
  "golden horns"
  ];
  $minor = Roller($featuremT00);
//d100 Traits: The dragon is...
$traitD00 = [
  "a dire dragon seemingly mutated someway by fell energies, larger and more violent than even most dragons",
  "the runt of the litter. It’s smaller than average and weaker, yet more intelligent and stealthy",
  "a new parent protecting its eggs. It is proud and excited for them but will protect them to the death",
  "part of a long family lineage of dragons and trying to live up to the expectations of that",
  "the survivor of an attack that haunts it. Whatever this attack was, it deeply disturbs the dragon whenever anything similar happens. For example, the dragon may freeze and panic around fire",
  "one half of a pair of twins. It is very connected to its twin",
  "fond of staying in humanoid form. It lives as a human, or similar race, living the normal life of a mortal and enjoying it greatly",
  "a powerful wild mage. It uses spells and breath attacks that often cause completely unexpected chaotic surges of magic",
  "a powerful wizard who has a large tome of magic. It adores magic and tries to learn as much as possible",
  "tainted by fiends, making it demonic and more evil than normal. The dragon is the lord of many minor demons that do its bidding",
  "tainted by celestials making it holy and good. The dragon is worshipped by many due to its holiness",
  "a fey dragon, giving it an affinity for the Feywild and to nature. It seems constantly surrounded by flowers and fairies and is quite the trickster",
  "an energetic builder who has actually tried to make its lair into the perfect dungeon. It will eagerly lure in and tempt people into it. It would even be excited if someone survived the entire dungeon",
  "a dire dragon seemingly mutated someway by fell energies, larger and more violent than even most dragons",
  "the runt of the litter. It’s smaller than average and weaker, yet more intelligent and stealthy",
  "a new parent protecting its eggs. It is proud and excited for them but will protect them to the death",
  "part of a long family lineage of dragons and trying to live up to the expectations of that",
  "the survivor of an attack that haunts it. Whatever this attack was, it deeply disturbs the dragon whenever anything similar happens. For example, the dragon may freeze and panic around fire",
  "one half of a pair of twins. It is very connected to its twin",
  "fond of staying in humanoid form. It lives as a human, or similar race, living the normal life of a mortal and enjoying it greatly",
  "a powerful wild mage. It uses spells and breath attacks that often cause completely unexpected chaotic surges of magic",
  "a powerful wizard who has a large tome of magic. It adores magic and tries to learn as much as possible",
  "tainted by fiends, making it demonic and more evil than normal. The dragon is the lord of many minor demons that do its bidding",
  "tainted by celestials making it holy and good. The dragon is worshipped by many due to its holiness",
  "a fey dragon, giving it an affinity for the Feywild and to nature. It seems constantly surrounded by flowers and fairies and is quite the trickster",
  "an energetic builder who has actually tried to make its lair into the perfect dungeon. It will eagerly lure in and tempt people into it. It would even be excited if someone survived the entire dungeon",
  "elf-styled mercenary, hunting down either heroes or evildoers. It hunts down these people and takes great pride in killing them",
  "fond of meditation and has spent years reaching inner enlightenment and tranquility",
  "very eager to make friends. Although making friends for a dragon often involves ‘playing’ with them in ways similar to a cat playing with a mouse",
  "trying to become the most infamous dragon in the entire realm, almost to the extent of making itself a brand",
  "part of a pair mated for life. They’re very unwilling to separate",
  "actually very stealthy. It will lay traps, bait an enemy, and then attack from the shadows",
  "undead but trying to cling to what it once was without losing its soul and its mind",
  "fond of meditation and has spent years reaching inner enlightenment and tranquility",
  "very eager to make friends. Although making friends for a dragon often involves ‘playing’ with them in ways similar to a cat playing with a mouse",
  "trying to become the most infamous dragon in the entire realm, almost to the extent of making itself a brand",
  "part of a pair mated for life. They’re very unwilling to separate",
  "actually very stealthy. It will lay traps, bait an enemy, and then attack from the shadows",
  "undead but trying to cling to what it once was without losing its soul and its mind",
  "not afraid of using technology. It has learnt from rock gnomes various steam and clockwork powered technologies, and it has created several auto turrets to use in its defenses",
  "highly religious. It worships its god or gods strongly and will go to the extent of performing great rituals or sacrifices",
  "the god-like leader of a cult of followers. It of course loves this as godhood strokes the ego",
  "highly emotional and will go through manic swings in its emotions. The dragon is kind and caring one day, and destructive the next",
  "the god-like leader of a cult of followers. It of course loves this as godhood strokes the ego",
  "highly emotional and will go through manic swings in its emotions. The dragon is kind and caring one day, and destructive the next",
  "connected to the environment around its lair in a profound way. It is able to manipulate the surrounding region, and it protects its territory fiercely",
  "a mad scientist that uses arcane magic to do twisted experiments on itself and others. Its lair is full of these experiments",
  "party to an agreement with a monster-hunting guild to kill those applicants that get annoying after they pay in their initial application payments",
  "respectful of mortals and smaller creatures. It sees meaning in all life, even something as small as an insect",
  "a king of a small land. The dragon wears a crown, and may be a harsh king, but the locals wont argue with a dragon",
  "respectful of mortals and smaller creatures. It sees meaning in all life, even something as small as an insect",
  "a king of a small land. The dragon wears a crown, and may be a harsh king, but the locals wont argue with a dragon",
  "very interested in medicine and will heal and fix up anyone near death, even those trying to kill it. They will then keep them in a dungeon until they regain strength",
  "almost entirely feral and primal",
  "fond of living in animal form, experiencing the wild. It has picked up many animal-like traits due to this",
  "extremely intelligent, or thinks it is. It tries to use its mind to solve problems, and, of course, it thinks it’s better at this than everyone else",
  "very charming and charismatic. It will actually talk its way out of, or into, sticky situations",
  "almost entirely feral and primal",
  "fond of living in animal form, experiencing the wild. It has picked up many animal-like traits due to this",
  "extremely intelligent, or thinks it is. It tries to use its mind to solve problems, and, of course, it thinks it’s better at this than everyone else",
  "very charming and charismatic. It will actually talk its way out of, or into, sticky situations",
  "not a blood-born dragon, but it was created by magic or some other source. This makes it confused about its life and creation",
  "adopted. As a wyrmling, it was raised by mortals. If they were kind, the dragon loves mortals. If they were cruel, the dragon harbors a hatred for mortals that borders on madness",
  "completely insane. Perhaps, this was caused by magic or some kind of drug abuse",
  "adopted. As a wyrmling, it was raised by mortals. If they were kind, the dragon loves mortals. If they were cruel, the dragon harbors a hatred for mortals that borders on madness",
  "completely insane. Perhaps, this was caused by magic or some kind of drug abuse",
  "more comfortable in flight than on the ground. It tries to touch the ground as little as possible. It even flies in its sleep, hovering above the ground",
  "unable or unwilling to fly. It never leaves the ground, despite having wings. The dragon has learnt to burrow instead when other dragons might fly",
  "extremely fast and agile, but not particularly strong. The dragon is able to dish out many attacks at one go that deal small but biting damage",
  "slow, lumbering, but deadly. When this dragon eventually gets to combat, its blows are highly destructive",
  "honorable. It has a strange honor code, only ever wanting to fight when it follows its precise set of rules. When people break this code, the dragon gets angry and unleashes its true power",
  "a member of a community. The dragon is part of a large community of friendly, or not so friendly dragons, who send messages and gifts to each other on a regular basis",
  "sleeping. It hibernates for centuries at a time… leading to a lot of confusion. Its snoring is so loud it is mistaken for wind",
  "sleeping. It hibernates for centuries at a time… leading to a lot of confusion. Its snoring is so loud it is mistaken for wind",
  "false. The dragon tries to be the opposite alignment of its natural state… While it tries hard, it still feels urges and can lose control",
  "a singer and composer. It considers itself a master bard and will write songs and music. The music may be good, but dragons are not the best at singing or playing the lute",
  "cursed with vampirism. While this doesn’t work exactly the same as with humanoids, it has given the dragon a ceaseless hunger for blood",
  "cursed with lycanthropy. While it doesn’t work the same as with humanoids, the dragon is amazingly violent beneath a full moon, and it hates silver",
  "terminally ill and is either trying to help or to hinder the world as much as possible in its dying days",
  "an exotic merchant. It runs a shop for those customers that are strong enough or clever enough to survive the trip through its lair",
  "a brilliant mastermind, a game master that plays with its pawns in one huge game, a game of dungeons and dragons",
  "mostly lawful. It follows ‘the law’ of the land, but it might occasionally stretch laws to allow it do what it wants",
  "greedy but appreciative. It will be kind to those that give it gifts that it deems exciting enough",
  "a lusty beast, which can be rather dangerous especially when it gets its eye on a party member",
  "a kingpin. It employs adventurers or mercenaries across the land, giving them funds to do things the dragon is simply to lazy to do",
  "a glutton for food, drink, and just about everything",
  "full of pride and vanity. This dragon has trouble looking away from the mirror",
  "greedy, moreso than most dragons. If anyone has any treasure in any way, the dragon needs it",
  "lazy. Why do anything when you can rest? It doesn’t want to bother any one as much as it just wants to sleep and be left alone",
  "vengeful. If someone wrongs this dragon even slightly, it will come at them, their children, their children’s children as well as every town they have been through ever",
  "a guardian. It is protecting a powerful artifact of intense magical power",
  "lonely, and only wants to find friends",
  "a bully. It bullies all the other dragons and monsters in the area, becoming their leader",
  "paranoid. It works intensely on illusions and creates illusionary traps and environments",
  "a thug. It demands protection money and food from nearby settlements",
  "very shy. It suffers from severe social anxiety and doesn’t want to talk to anyone",
  "conniving. It enjoys traipsing about in its human form, influencing the entire realm and doing dark dealings",
  "a homebody. It only leaves its lair during a certain season each year",
  "a fame-seeker. It wants to die in such a way that legends and songs will be created after it. It may actually try and orchestrate this",
  "sick with the flu. A dragon sneeze is a powerful, but embarrassing weapon"
  ];
  $trait = Roller($traitD00);
//d100 Speech: When it comes to conversation, the dragon...
$speechD00 = [
  "is offended by those who will not speak Draconic, and it refuses to speak in any other tongue",
  "knows many languages and loves to talk",
  "is mute or refuses to talk",
  "talks very slowly and conservatively",
  "speaks its mind very simply",
  "speaks only in riddles and metaphors",
  "tends to ask constant questions but give no answers",
  "is very flirty. Uncomfortably so",
  "mimics anyone that talks to them",
  "will find any excuse to argue",
  "uses its breath weapon as violent punctuation",
  "speaks using illusions like charades",
  "is very friendly until someone swears and then is extremely offended and angry",
  "laughs darkly almost whenever possible",
  "growls out most of its words",
  "speaks very broken language",
  "refers to itself in third person",
  "only speaks through a scribe interpreter",
  "gets uncomfortably close as it speaks",
  "seems to know everything about everyone it talks too"
  ];
  $speech = Roller($speechD00);
//d100 Hoard: Each dragon is compelled to hoard what it treasures, and this dragon’s hoard is...
$hoardD00 = [
  "a sea of gold and silver coins",
  "gold, but only the currency of one race, and oddly not the race in the nearby areas",
  "Carefully organized; money is in neat stacks and every treasure is organized using a complex system",
  "all famous art, paintings and statues. It will commission paintings of itself, and go to art shows in disguise",
  "food. The dragon loves to eat and sees food as a potential to be an art form. It actually hires chefs to cook the best food possible",
  "the frozen or petrified statuesque forms of adventurers that tried to kill it. It will tell the tales of their attempts proudly and with great interest",
  "stories and legends. It loves to hear and tell stories and has an obsession with bards",
  "music. It constantly needs music playing in its lair, and it gets very agitated if there is none",
  "a zoo of various monsters and creatures. It aims to have two of every race at one point, male and female",
  "buildings. This dragon hoards real estate and territory. In disguise, it owns and buys land. The land is more important than the people that live there, but it will help the people if it helps them get more land",
  "gemstones. This dragon has little time for money but loves gemstones. Preferably cut",
  "a library of books and stories. Knowledge is its passion",
  "magical artifacts from all across the world",
  "a very beautiful mansion that it uses like a doll house, furnished with the finest in appearance and luxury",
  "people it deems interesting that it either enslaves or convinces to stay",
  "narcotics. The dragon loves to try different types of drugs, such as pipeweeds and psychotropic mushrooms. Of course it needs to take a large dose to gain the desired effect",
  "a large and beautiful garden that it keeps and tends",
  "its children. The dragon has many pure and half-blood children and takes care of them lovingly",
  "potions and all kinds of strange alchemical creations",
  "the corpses and remains of other dragons. The dragon is particularly interested in weapons and armors made of dragonscales",
  "artisan jewelry that the dragon actually wears on its body",
  "literally everything. This leads to this dragons hoard being very random and chaotic",
  "objects of power linked to its element",
  "minions that swear loyalty to the dragon",
  "gemstones and other things that are the same color as the dragon",
  "very sparsely laid out over many rooms with a single treasured object in each room",
  "very dense and compact with a large amount of treasure forced into one small room",
  "hidden. The dragon assumes visitors intend to steal its treasure",
  "up for being shared. The dragon will often share its hoard to those that need it, endorsing heroes. Often though, this is a loan to be repaid",
  "vast and very old. The hoard has been passed down for several generations"
  ];
   $hoard = Roller($hoardD00);
//d100 Lair: This dragon’s lair is...
$lairD00 = [
  "an ancient ruin from an ancient race",
  "on the peak of the tallest mountain with few paths leading up to it",
  "a temple built for the dragon personally by its worshippers or slaves",
  "on a flying island above the land. Barren, it is a very safe and secure place",
  "on a flying island above the land. Lush, it is a very safe and secure place",
  "in the underwater wreckage of a galley, perhaps with caverns and ruins below it",
  "an abandoned mine. The mineshafts are filled with minions who defend the dragon",
  "a cavern carved out of stone by the dragon itself. The walls are full of these sharp cuts scraped by the dragon and the chambers are of a size that matches the dragon’s wingspan",
  "a reclaimed castle. The surrounding area are plains and the castle was most likely abandoned by its old owners",
  "a reclaimed castle. The surrounding area is a desert and the castle was most likely abandoned by its old owners",
  "a huge pyramid, surrounded by dangerous deserts",
  "a giant tree, perhaps dead. A tree large enough to hold a dragon is impressive",
  "a giant tree, in a lush environment. A tree large enough to hold a dragon is impressive",
  "in a series of Underdark caverns. The Underdark can be a great place for a dragon that’s trying to hide away",
  "inside a volcano. The heat is quite comfortable for a fire-breathing dragon, but also provides defense from attackers",
  "an abandoned settlement. The towns walls now protect the dragon who claims the empty town",
  "a tomb. The dragon has little respect for the dead of mortals, so the tomb’s layout has proved a useful lair",
  "on a lonely island away from most of the world",
  "a structure built by its minions with a ramshackle base. It seems like it will fall apart at any time",
  "atop a high, flat mesa that is perfect for dragon duels",
  "behind a waterfall. The falls hide the entrance to the large cave system in which the dragon lairs",
  "no where. The dragon is nomadic and has no fixed home, always travelling for some reason",
  "a large roost community of several young dragons",
  "a pocket dimension of its own creation",
  "a realm designed to imprison it, perhaps the dragon took control of the realm after its imprisonment",
  "on an elemental plane linked to the dragon",
  "a citadel designed to imprison the dragon, and perhaps also other beings of similar power waiting to be freed",
  "on the site of a great battle. The ground littered with corpses, making an unsettling stomping ground for a dragon",
  "a ravine where the dragon can enter with ease",
  "built by the dragon. The best homes are made yourself",
  "on an arctic glacier, cold and far away",
  "underneath a settlement, likely hidden from most of the population",
  "a mountain top shrine"
  ];
   $lair = Roller($lairD00);
//d100 The dragon’s lair also has...
$lair2D00 = [
  "a place of magical power, a ley line that lets the dragon tap into raw magic",
  "a place of elemental power",
  "a portal between realms",
  "skinned monsters in every hallway. The decorator has a macabre sense of style",
  "a library of ancient tomes",
  "a room of the dragon’s concubines of various races",
  "puzzles that requires a dragon’s strength to operate",
  "arcane traps",
  "murals of the dragon’s personal conquests",
  "a clutch of dragon eggs",
  "illusions playing tricks on all that enter",
  "scaly-skin molted all over the floors",
  "a fake hoard filled with a sea of coin mimics",
  "several holes in the roof through which the dragon can enter and exit while in flight",
  "friendly inhabitants that live with the dragon",
  "many statues and paintings of the dragon",
  "maze-like corridors",
  "puzzles that are easy if one understands Draconic",
  "a huge chess set with pawns the size of people",
  "the bones of one of the dragon’s parents",
  "warding stones outside from several races warning of danger",
  "a ghost bound to guard the lair and politely turn away invaders",
  "a cloud of smoke and mist around it at all times",
  "a huge pantry of all kinds of raw meats",
  "an illusory dragon to bait enemy spells and attacks",
  "strange music traveling throughout the whole lair",
  "an alarming amount of mold and decay",
  "strange and violent weather in its vicinity at all times",
  "flooded caverns full of waterborne monsters",
  "one huge chamber with pillars breaking it up"
  ];
   $lair .= " that also has ".Roller($lair2D00);
//d100 Henchmen: Their lair is defended by...
$minionD00 = [
  "goblins who worship the dragon out of fear. The dragon does not care for their lives and hires them en masse",
  "mercenaries hired by the dragon to keep it safe. The races and skills do not matter to the dragon, so they may be a mixed bunch",
  "hobgoblin soldiers, highly trained professionals",
  "the dragon’s children, including purebred dragons and half-dragon creatures",
  "the nightmares of all that enter",
  "kobolds with the intelligence of toddlers. They just want to help",
  "mortal cultists",
  "a sect of mortal dragon knights",
  "wild beasts, lured in by the dragon",
  "intelligent beasts",
  "mephits and elementals suiting the dragon",
  "genasi linked to the dragon’s element",
  "undead",
  "fiends",
  "shadowy versions of the party raiding the dungeon",
  "seemingly harmless warning signs that hold deadly curses for those who approach",
  "terrified peasants",
  "arcane defense turrets",
  "giant Insects",
  "smaller dragon-like creatures"
  ];
  $minions = Roller($minionD00);
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dragons | Tables</title>
  </head>
  <body>
    <h2> The Dragon Legend </h2>
    <p>
    <b><?=$name?></b> is <b><?=$age?></b> <b><?=$color?></b> and it has <b><?=$mayor?></b>, it also has  <b><?=$minor?></b>. It is <b><?=$trait?></b>, that when it comes to conversation <b><?=$speech?></b>.<br>
    Its hoard is <b><?=$hoard?></b> stored on its lair that is <b><?=$lair?></b> and is defended and populated by <b><?=$minions?></b>.
    </p><br>
  </body>
</html>
