<?php require_once("math.php"); ?>

<?php
//Table 7–50: Undiscovered Islands
$islandD00 = [
  "an island with beaches full of smooth, multi-colored glass pebbles instead of sand",
  "a coral atoll that absorbs sunlight during the day and then glows at night",
  "a reef ruled by warring kingdoms of sentient crabs",
  "the rocs’ graveyard",
  "an island filled with ruined temples dedicated to forgotten gods from every corner of the world",
  "an island almost entirely made up of old shipwrecks",
  "a frigid island in the far north filled with countless misshapen monsters trapped within its ice",
  "an island with many spouts and jets of colored flame",
  "a floating island that travels wherever the wind blows",
  "an island where sentient beings and their possessions get shrunk down to 1/60 their normal size",
  "an iceberg topped with an ice castle",
  "an island whose inhabitants languish in a dreamy haze from a powerful narcotic plant grown there",
  "an island filled with huge stone idols of unknown origin and purpose",
  "a sandy islet filled with buried skeletons that rise up and attack anyone landing on the beaches",
  "an island of cannibal apes",
  "an island formed from the rotting corpses of two giant dragons who crashed while locked in combat",
  "a northern island where ice and snow have all the colors of the rainbow",
  "an island with trees that behave like natural siege artillery, firing enormous nuts and fruit at ships passing too close to shore",
  "a caldera with bubbling sea-geysers inside its rim",
  "an island that is one giant cathedral",
  "an isle of the Dead, necropolis island occasionally glimpsed by travelers",
  "a fey island that occasionally rises from the depths of an isolated loch",
  "an island where the ghosts of fallen stars wait until the end of the world",
  "an island of impossibly high cliffs whose interior has never been explored",
  "an iceberg with a ship trapped within it"
  ];
   $island = Roller($islandD00);

//Table 7–51: Pieces of Interesting Flotsam
$flotsamD00 = [
  "an empty raft",
  "a message in a bottle",
  "a ship in a bottle",
  "a bloated, decaying kraken carcass",
  "a dragon turtle shell",
  "a ship’s figurehead depicting a bloated green frog",
  "a mermaid caught in a fisherman’s net",
  "an island of shipwrecks occupied by gargoyles",
  "a raft with two mummies aboard",
  "a charred oar",
  "a coracle containing three skeletons",
  "a rowing boat with two gibbeted corpses",
  "the remains of a keelhauled ogre",
  "three dead trolls choked with seaweed",
  "a corked, empty potion of water breathing vial",
  "the remains of a howdah",
  "a complete caravel, seemingly abandoned hastily",
  "a corroded copper teakettle",
  "a model clipper ship filled with lead miniatures",
  "a wicker sofa frame with a single cushion still attached",
  "a fire-seared totem pole",
  "a buoy with the word “Help!” scratched on it",
  "a clothesline, linens, and two cracked poles",
  "a maiden’s ransacked hope chest",
  "a wooden cage filled with drowned homing pigeons",
  "a wooden scabbard wrapped in white silk",
  "a floating ship’s nameplate: The Lucky",
  "a basket bearing a single mewling kitten",
  "a lifeboat containing hundreds of waterlogged wigs",
  "a severed arm chained to a broken oar.",
  "a lute with the inscription, “Let the Heavens weep”",
  "a scroll case inscribed with the letters “SofV”",
  "a chest filled with shards of cuneiform tablets",
  "a wooden ship’s altar defaced with a shamrock brand",
  "an upturned leather hat occupied by a spider",
  "a hollowed bottom of a pumpkin the size of carriage",
  "gulls feeding on a drying rack filled with rotten fish",
  "a small wharf, complete with a deckchair",
  "a wooden steeple, its bell still chiming",
  "a washed-away bridge",
  "a floating isle of lashed flotsam",
  "a lobster trap, with 1d4 lobsters inside",
  "a set of false teeth sized for a giant",
  "a thick board hung with common carpentry tools",
  "a copper bathtub",
  "a healer’s kit labeled “Seasickness Pills”",
  "a pair of leathery wings",
  "a set of man-made wings, with roc feathers attached",
  "an inflated pig’s-bladder ball",
  "a sail with a large, perfectly round hole in its center"
  ];
   $flotsam = Roller($flotsamD00);

//Table 7–52: Ghost Ships and Shipwrecks
//d% Ship Name and Description
$ghostD00 = [
  "The Angry Drake: a half-sized kobold warship",
  "The Sparrow: a colossal axe lies buried in the hull of this ship",
  "The Luckless: rotten carcasses litter the beach while broken remnants of this ship wash ashore",
  "The Endless: the zombie crew of a shipwrecked ghost ship stagger in a storm",
  "The Vile Axe: an orc warship lies broken on the cliffs, her vampire captain nowhere to be seen",
  "The Funerary Barge: why has no one tried to retrieve the obvious gold and jewels littering this ship’s deck?",
  "The Visitor: some say this fey boat emerges from the tide some days, while others claim it sails on dark seas",
  "The Storm: this dhow has completely broken in two, as if it was bitten in half",
  "The Blue Ferret: seemingly crushed, this ship has a kraken’s tentacle mummifying on its mast",
  "The Green Misery: this broken ship lies strangled by ivy in a lagoon",
  "The Dragon’s Spine: how did the broken remnants of this caravel wash up 20 miles inland?",
  "The Peacock and Leopard: this hag’s ship looks like a torture chamber—is it as empty as it seems?",
  "The Javelin: the charred mast suggests a lightning storm, but the log claims it happened on a clear night",
  "The Hogshead: this eerily silent plague ship drifts ever closer to shore",
  "The Splenterwill: this goblin frigate lies upside down on the beach",
  "The Night Belle: gnawed remains indicate that the crew ate one another, but still had plenty of supplies",
  "The Broadsword: mutiny tore this warship apart before her wizard captain blew it to pieces",
  "The Libertine: the wreck of a harem boat occupied by hags and zombie harlots",
  "Urloo’s Fate: every living creature on this vessel was changed into a glass statue too fragile to move",
  "The Robust: the hands and feet of every member of the crew have been nailed to the prow",
  "The Dalmatian: the ghost of a wrongfully hanged sailor killed the rest of the crew and now waits for fresh victims",
  "The White Herald: royals fled from the revolution but could not elude the fiend sent to slaughter them",
  "The Sprat: a wide barge cursed by underwater harpies lies ruined beneath the waves",
  "The Crystal Ball: fire killed the crew, but most of the ship’s structure remains relatively intact, if charred",
  "The Graycloak: convicts managed to take control of this prison ship, but not before the guards triggered the failsafe that trapped and sunk the ship",
  "The Constellation: a collision with an iceberg left the crew of this frozen barque trapped and starving",
  "The Saucy Strumpet: pirates lost a fight and the victors set them adrift after hanging the survivors",
  "The Broken Bough: the ghost of the dryad whose tree became the mast haunts this flowering wreck",
  "The Cutlass: nothing but clothes remain of the passengers and crew of this abandoned hooker",
  "The Titan: the anchor and anchor chain refuse to move; eventually the crew abandoned ship in disgust",
  "The Miracle: an enormous mimic-like creature that drifts into port and eats any crew that claims it",
  "My Heart’s Desire: thieves took over the local lighthouse and lured this ship into a reef",
  "The Foamfriend: the crew managed to beach this ship before it sank",
  "Gordor’s Hammer: this warship took out two of the enemy before crashing into a third; debris from all four now mingles in an island lagoon",
  "The Percival: a strange artifact might offer a clue as to how this vessel managed to crash miles from any water",
  "The Lightbringer: the holy symbols on the sail didn’t preserve this ship from sacrilegious pirates",
  "The Tider: glimpsed through murky water, the crew are still at their posts and moving on this sunken cog",
  "The Wildcard: creeping vines hint at how long this floating casino has lain abandoned on the river bank",
  "The Independence: this scourge of slavers met its end through treachery in a supposedly safe harbor",
  "The Sandspider: the lich who rules the island where this ship lies actually creates the treasure maps that lure so many adventuring bands to their doom",
  "The Cornucopia: pleasure ship whose hull is intact, but everything inside has been eaten",
  "The Docent: this menagerie transport vessel crashed onto an island now legendary for deadly beasts",
  "Nefas Pedimin: this schooner, made from bones, terrorized the seas until a sorcerer broke its magic",
  "The Festering Vaid: this ship is completely covered in cankerous black lichens",
  "The Last Laugh: tainted food drove the crew of this pleasure yacht mad, causing most to jump overboard",
  "The Open Book: the university that sponsored this vessel lost its investment when cannibals attacked",
  "The Glimmer: this fishing vessel caught something with a blade, which cut the net and slaughtered the crew",
  "The Poniard: the warriors laid to rest on this ship never got their proper funeral since it failed to burn",
  "The Twilight Eternal: this plane-shifting galleon returned from its dimensional shortcut without its crew",
  "The Maltmainge Tomorrow: still, silent crows perch upon every part of this well-preserved ship"
  ];
   $ghost = Roller($ghostD00);

//Table 7–53: Sailors and Boatmen
//d% Name and Description
$crewD00 = [
  "Sing-Song Sane: the singing ferryman who knows 100 songs; sings a different one for every passenger",
  "Cruel Kate: harlot with a heart of steel; foulmouthed whore who operates the riverboats",
  "Zanus the Troubadour: poetry-quoting gnome who punts customers up and down the river",
  "Pike Pilkly: the human fish, a champion swimmer rumored to have gills",
  "Big Dill: strongest dockhand in the world, said to have hill giant blood in his veins",
  "Ancient Hubert: the 200-year-old man, as full of stories as his mouth is empty of teeth",
  "Captain Rhun: mad pirate captain (retired); only his mangy ship’s dog will sit with him",
  "Bletko Brothers: former acrobats, their work in the rigging is something to see",
  "Blind Jake: blind old sailor who knows the rigging like the back of his hand",
  "Bilgewater Bully: sailor who searches slops and bilges for lost treasure",
  "Hobble: lost his legs to a shark, but says he can do anything a whole man can",
  "“Coffin” Janu: morbid crewman who brings his casket with him whenever he goes to sea",
  "Old Bonesy: skeleton of former shipmate no one has the heart to throw overboard",
  "Nassain Lastleaf: grim elf wanderer who claims his homeland disappeared beneath the waves",
  "“Mister” Smarts: 10-year-old midshipman who never hesitates to order floggings for sailors who displease him",
  "Brionny Fortin: would-be mermaid who spends her off hours gazing dreamily into the depths",
  "Argus No-Beard: disgraced dwarf harpooner who shaves daily but never misses his target",
  "Xericuse: gloomy stargazer who spends his nights studying the skies",
  "Wavrin: murderous cook who poisons selected crewmates as secret sacrifices to an evil sea god",
  "Lasselle: peg-legged mutineer who blames the captain for his injury and plots a mutiny as revenge",
  "Kristot: merchant logger who pilots a raft of fresh timber and trade goods downstream",
  "Jinit Beiderdan: runaway bride who fled an arranged marriage to sail around the world",
  "Skerrit Scalesinger: fish charmer; fish actually leap up onto the deck when he sings",
  "Eldrea Porto: misguided missionary who lectures the crew and people in port about the “truth”",
  "Bintrin Whist: harmonica virtuoso who earns his keep with music rather than sailing skills",
  "Flora Kain: amateur naturalist who collects and preserves insects from every port of call",
  "“Blessed” Prig: lucky halfling; no one ever dies so long as he remains on board",
  "Moira DeLang: ship-wife who offers comfort to lonely sailors for a fee",
  "Dask: half-orc brawler who takes on all comers but demands one copper from each spectator",
  "Ophaira Yimmer: sarcastic puppeteer who entertains crew but negatively portrays officers",
  "Saladin Greel: fearless marine who boards enemy ships with a bloody cutlass in each hand",
  "Samdin Garah: half-elf spy sent by the government to investigate reports of officers abusing sailors",
  "Twilla Gorn: peerless navigator who never gets lost but refuses to explain her secret",
  "Dravin Corst: murderous riverman who strangles passengers with the silk cord he keeps wrapped around his pole",
  "“Doc” Ferrin: amateur medic; a bankrupt tailor who learned how to stitch up his fellow sailors when he put to sea",
  "Great Gabwell: huge man who looks like a pig, and eats like one too",
  "Starg the Survivor: sailor who has survived no less than three keelhaulings",
  "Gorus Bain: connected gondolier who knows which boats and wharves cater to which vices",
  "“Heartbreak” Hinsin: sailing lothario who has a love interest in every port of call",
  "Argin Willster: story-telling boatman who has an endless supply of stories about his vast family",
  "Voris Uld: master carver who makes beautiful pieces of scrimshaw and wood but only while at sea",
  "Mesner Taim: entrepreneurial boatman who offers a wide range of additional services to passengers",
  "Brenn: exploration addict who always wants to get to a new destination",
  "Burlon Afarn: joke wizard; crewmates enjoy teasing him about his imaginary magical powers and bilge rat familiar",
  "Labella Loor: sneak thief who steals small valuables with her trained raven",
  "Shandir Zim: plague carrier, chosen by the god of disease to spread contagion wherever he goes",
  "Captain Simms: once wrestled a kraken",
  "Captain Flashwell: the biggest boaster on the Seventeen Seas",
  "Captain Thonn: dwarf captain with gold teeth and two hooks for hands",
  "Captain Z’gark: legendary hobgoblin sea captain; not an inch of his flesh is unscarred"
  ];
   $crew = Roller($crewD00);

//Table 7–54: Types of Boats and Ships
//d% Boat Type and Description
$boteD00 = [
  "Barge: flat-bottomed freight boat",
  "Barque: large ship with multiple masts",
  "Bireme: ship with two tiers of oars",
  "Brig: ship with two masts with square sails",
  "Canoe: small, light boat propelled by paddles",
  "Caravel: maneuverable sailing ship with multiple masts",
  "Carrack: seagoing ship with three or four masts",
  "Clipper: fast ship with multiple masts",
  "Coracle: small wickerwork boat",
  "Curragh: hide-covered version of coracle",
  "Cutter: small ship with single mast",
  "Dhow: coastal vessel with lateen sails",
  "Dinghy: small sailing vessel",
  "Dory: small, flat-bottomed fishing vessel",
  "Dragon boat: long, narrow canoe",
  "Dugout: canoe made from hollowed out tree trunk",
  "Fireboat: firefighting boat",
  "Galleon: large multi-decked sailing ship",
  "Galley: large ship propelled by oars",
  "Gondola: flat-bottomed boat worked by single oar",
  "Hooker: sailing and fishing boat designed for high seas",
  "Houseboat: boat outfitted as a floating house",
  "Jolly boat: small clinker-built boat",
  "Junk: flat-bottomed seagoing vessel",
  "Kayak: one-man canoe with light frame",
  "Keelboat: flat-bottomed river vessel",
  "Koch: sailing ship designed for icy conditions",
  "Knaar: seagoing merchant vessel with single mast",
  "Lifeboat: boat designed to aid vessels in distress",
  "Longboat: boat used to reach shore from larger vessels",
  "Longship: long, narrow ship with single mast",
  "Lugger: small ship with four sails",
  "Narrow-boat: canal boat with narrow beam",
  "Pinnace: small vessel with two masts",
  "Pontoon: flat-bottomed boat used to support structures",
  "Punt: flat-bottomed boat for shallow rivers",
  "Raft: collection of logs fastened together",
  "Sampan: small river and coastal boat",
  "Schooner: small, seagoing fore-and-aft rigged vessel",
  "Scow: large, flat-bottomed, square-ended boat",
  "Skiff: small, light boat for rowing and sculling",
  "Sloop: small, fore-and-aft rigged vessel with one mast",
  "Tall ship: large, traditionally rigged sailing vessel",
  "Trireme: warship with three tiers of oars",
  "Trawler: vessel used for fishing with trawling net",
  "Warship: ship built for combat",
  "Whaleboat: ship used for hunting whales",
  "Windjammer: large sailing ship with iron hull",
  "Yacht: recreational boat",
  "Yawl: sailing vessel with one mast"
  ];
   $bote = Roller($boteD00);

//Table 7–55: Captains and Ships
//d% Captain Ship
$captainD00 = [
  "'Coral Mouth' Kate captain of the Adventurous",
  "'Gullmouth' Garault captain of the Arcadia",
  "'Piebald' Paultz Patches captain of the Avalanche",
  "'Ruddernack' McGee captain of the Bilgerat",
  "Ace 'Birdbelly' Stogen captain of the Bluewater",
  "Aggie Gams captain of the Bunyip",
  "Amalia 'Huntress' Steerwright captain of the Dagon's Bastard",
  "Anthropius 'Fox' Maciason captain of the Emperor",
  "Antoine Seabourne captain of the Faith Wife",
  "Arvey Blacktongue captain of the Flotsam",
  "Bartz Boilston captain of the Fogbringer",
  "Benson the Hulled captain of the Gallant",
  "Bilge-Splash Becks captain of the Garland",
  "Bilgewater Pete captain of the Gestalt",
  "Chesk Wilverton captain of the Gold Fever",
  "Cidian Whitch captain of the Gorum's Hammer",
  "Eldam Alamansor captain of the Hale & Hearty",
  "Givvi Meanteeth captain of the Hangman",
  "Groman Flanck captain of the Heron",
  "Harval Spue captain of the Hook",
  "Higg Ribbelby captain of the Koriander's Wrath",
  "Hosk 'Sevenfingers' Legrau captain of the Largeness",
  "Ijora 'The Storm Seer' Ettzi captain of the Madeleine",
  "Ilana Whistler captain of the No News",
  "J. E. Ritter captain of the Penora's Pride",
  "Jivvis 'Codhead' La Rupe captain of the Pharasma's Messenger",
  "Keelboat Bill captain of the Pinkbelly",
  "Kelps Muggin captain of the Rabid Kraken",
  "Lady Amyretha Quintalian captain of the Ravenscar",
  "Larz Rivengob captain of the Riptide",
  "Luthron 'The Pelican' Abele captain of the Ruby Porpoise",
  "Mucks Fallahan captain of the Ruddy Wreck",
  "Myra 'The Carver' Sinsashi captain of the Rum Runner",
  "Orem 'Fishlips' Yenessi captain of the Scurvy Crab",
  "Papa Barnacle captain of the Sea Weasel",
  "Peg-leg Peggy Potts captain of the Silver Bird",
  "Rip Carrington captain of the Skora's Ire",
  "Rufus Longwater captain of the Splinter",
  "Sags Sureslung captain of the Squaller",
  "Shanks Guffy captain of the Starsail",
  "Sherven Twobeards captain of the Starsinger",
  "Sir Apeldine Gantry captain of the Sunfish",
  "Skriv Tentooth captain of the Three Sheets",
  "Spits Bascap captain of the Typhoon Lotus",
  "Taggart Brockson captain of the Undaunted",
  "Thalina 'Sea-Bitch' Andyll captain of the Walrus",
  "Theodore the Stained captain of the Waterstrider",
  "Westin Gale captain of the Waveraker",
  "Xobost Ietzam captain of the Western Promise",
  "Zhar Slitshanks captain of the Winter's Bite",
  ];
   $captain = Roller($captainD00);

?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sea Adventure | Pathfinder | TE</title>
  </head>
  <body>
    <h2>Sea Adventure</h2>
    <p>
      You are a crewmember under <b><?=$captain?></b>, traveling with <b><?=$crew?></b> who sails on the <b><?=$bote?></b>.<br>
      On your way to <b><?=$island?></b> you find <b><?=$flotsam?></b> just before faceing  <b><?=$ghost?></b>.<br>
      <br>
      <br>
      <br>
    </p>
  </body>
</html>
