<?php require_once("math.php"); ?>
<?php
//Random Golems
//d12 The golem is...
$modD12 = [
  "tiny",
  "compact",
  "humanoid",
  "four-legged",
  "enormous",
  "shifting",
  "thickset",
  "willowy",
  "round",
  "foldable",
  "paunchy",
  "slight"
  ];
   $mod = Roller($modD12);
//d100 ...and made of...
$matD00 = [
  "clay",
  "clay",
  "clay",
  "rock",
  "rock with gems",
  "rock",
  "iron",
  "iron",
  "iron",
  "rusty steel",
  "molten steel",
  "steel",
  "titanium",
  "orichalcum",
  "glass",
  "bone and tooth",
  "bone and tooth",
  "bone and tooth",
  "ivory",
  "wood",
  "chalk",
  "blooded ice",
  "packed ice",
  "ice",
  "gold",
  "silver",
  "bronze",
  "copper",
  "brass",
  "ornamented brass",
  "rusty brass",
  "dirt",
  "grass and vines",
  "sky iron",
  "scarletite",
  "diamond",
  "garnet",
  "amethyst",
  "transparent flesh",
  "roten flesh",
  "flesh",
  "shaped Souls",
  "quartz",
  "quartz",
  "quartz",
  "obsidian",
  "opace obsidian",
  "shatered obsidian",
  "rusty chains",
  "broken chains",
  "chains",
  "ash",
  "gears",
  "magnetic rock",
  "mud",
  "mud",
  "mud",
  "web",
  "demonic flesh",
  "scales",
  "dragonbone",
  "hellfire",
  "sand",
  "sandstone",
  "winded sand",
  "marble",
  "marble",
  "craked marble",
  "books",
  "straw",
  "coral",
  "amber",
  "shadow",
  "lightning",
  "blood glob",
  "rope and string",
  "jelly",
  "wax",
  "water",
  "slate",
  "plastic",
  "fur",
  "quicksilver",
  "honey",
  "locusts",
  "paper",
  "fabric",
  "vapour",
  "mercury",
  "aluminium",
  "platinum",
  "tin",
  "tin",
  "rusted tin",
  "a gravestone",
  "bricks",
  "springs",
  "feathers",
  "vegetables",
  "sponge"
  ];
   $mat = Roller($matD00);
//d20 The golem is powered by...
$powerD20 = [
  "clockwork",
  "steam",
  "bound souls",
  "a magical-mechanical rune system",
  "divine will",
  "a purpose inherent to the universe",
  "arcane force",
  "a system of weight lifts and pendulums",
  "life Essence",
  "electricity",
  "tapping into mana veins",
  "a reality shaping spell",
  "elementals",
  "strings to a puppet master",
  "sunlight",
  "food",
  "a symbiote",
  "fuel combustion",
  "the wind",
  "liquid pumps"
  ];
   $power = Roller($powerD20);
//d6 The golem...
$ageD6 = [
  "is brand new",
  "is recent",
  "has been around for a while",
  "is old",
  "has been roaming from the dawn of time",
  "is ancient"
  ];
  $age = Roller($ageD6);
//d100 The golem was built for...
$purposD00 = [
  "mining",
  "guarding",
  "soldiering",
  "defending",
  "forging",
  "mining",
  "guarding",
  "soldiering",
  "defending",
  "forging",
  "mining",
  "guarding",
  "soldiering",
  "defending",
  "forging",
  "alchemy",
  "carrying",
  "searching",
  "intimidating",
  "storing knowledge",
  "carrying",
  "searching",
  "intimidating",
  "storing knowledge",
  "carrying",
  "searching",
  "intimidating",
  "storing knowledge",
  "aesthetics",
  "hunting",
  "collecting",
  "farming",
  "constructing",
  "transporting",
  "policing",
  "collecting",
  "farming",
  "constructing",
  "transporting",
  "policing",
  "collecting",
  "farming",
  "constructing",
  "transporting",
  "policing",
  "exploring",
  "advising",
  "arena fighting for gold",
  "arena fighting as entretainment",
  "arena fighting",
  "healing",
  "powering",
  "entertaining",
  "sexual gratification",
  "teaching",
  "guiding",
  "recording",
  "drawing",
  "observing",
  "holding",
  "exterminating",
  "brewing",
  "tabulating",
  "informing",
  "illuminating",
  "fetching",
  "handling",
  "taming",
  "playing",
  "cooking",
  "sorting",
  "casting spells",
  "grave digging",
  "investigating",
  "breaking things down",
  "maintaining",
  "cutting",
  "protesting",
  "heating",
  "road building",
  "climbing",
  "stealing",
  "consuming",
  "reciting",
  "accounting",
  "following",
  "reading",
  "shearing",
  "tanning",
  "assembling",
  "monitoring",
  "flight",
  "keeping secrets",
  "deciphering",
  "spelljamming",
  "sealing",
  "sparring",
  "generating",
  "enchanting",
  "grinding"
  ];
   $purpose = Roller($purposD00);
//d20 The golem was created by...
$creatorD20 = [
  "A priest",
  "A lich",
  "A mage",
  "An artisan",
  "A god",
  "A demon",
  "A warlord",
  "A factory",
  "A general",
  "A king",
  "Nature",
  "A druid",
  "An alchemist",
  "A scholar",
  "A cultist",
  "A dragon",
  "A merchant",
  "A criminal",
  "An ealdorman",
  "An experimentalist"
  ];
   $creator = Roller($creatorD20);
//d8 Who imbued or equipped it with...
$imbuedD8 = [
  "most-absolute knowledge of magic",
  "most-absolute knowledge of creatures and plants",
  "most-absolute knowledge of alchemy and medicine",
  "most-absolute knowledge of strategy and tactics",
  "most-absolute knowledge of economics and craftsmanship",
  "most-absolute knowledge of people and cultures",
  "human-level speech",
  "true empathy",
  "an ability to manipulate",
  "language translation",
  "group psychology",
  "body language",
  "a grappling hook",
  "an automatic saw",
  "a powerful lamp",
  "a trap placer",
  "a number of hidden compartments",
  "a gyroscope of perfect balance",
  "night vision",
  "magical sensitivity",
  "acute senses",
  "truevision for 1km",
  "lie detection",
  "absolute direction",
  "rage",
  "melancholy",
  "sadness",
  "happiness",
  "fear",
  "hatred",
  "compassion",
  "rudeness",
  "curiosity",
  "aggressiveness",
  "joyfulness",
  "mischievousness",
  "demonic force",
  "holy force",
  "elemental force",
  "arcane force",
  "wild force",
  "void force",
  "the special ability to self-repair",
  "the special ability to resist extreme temperature",
  "the special ability of a self-destruct sequence",
  "the special ability of perfect memory",
  "the special ability of an alternate form",
  "the special ability to gain additional armour",
  "the special ability to summon a protective force field."
  ];
   $imbued = Roller($imbuedD8);
//d100 Distinguishing Feature: The golem has or is...
$featureD00 = [
  "an extra pair of limbs",
  "a vibrant and unusual colour",
  "the complete lack of any facial features",
  "an inability to move",
  "a set of predatory fangs",
  "a section that has been repaired with a different material",
  "glowing runes",
  "instructions written in a strange script displayed prominently",
  "rich and elaborate decorations",
  "the crest of a noble house",
  "the crest of an organization",
  "the sigil of a noble house",
  "the sigil of an organization",
  "a face made to resemble a real living or dead person",
  "brightly shining eyes",
  "a head shaped to resemble an animal's",
  "part of the head is shaped to resemble a crown",
  "been prominently built of a second material (roll again on materials table)",
  "it is designed to look like a statue",
  "obviously made by an amateur",
  "parts are chipped off or well worn",
  "colour differences seem to indicate being made in different stages",
  "it is inlayed with gems and precious metals",
  "magical strains and strings are visible",
  "overgrown",
  "wearing clothes",
  "no eyes",
  "its material is polished to almost mirror-like qualities",
  "its material was shaped to resemble a fancy hairstyle",
  "elaborate scrollwork",
  "carrier bags",
  "a single Cyclopean eye",
  "oddly shaped shoulders",
  "a veil",
  "hooks and eyelets placed all over",
  "a custom suit of armour",
  "etched geometric or themed patterns",
  "covered in fur",
  "reinforced joints",
  "some of the inner workings is visible",
  "a fan for heat dissipation",
  "it's designed to resemble a mythical creature",
  "a strange hum emanating from its core",
  ];
   $feature = Roller($featureD00);
//d4 The golem defends itself with...
$defenceD4 = [
  "a massive hammer",
  "unarmed combat",
  "sharp twin blades",
  "a spear",
  "a broadsword",
  "a battleaxe",
  "a fixed repeater crossbow",
  "a mounted catapult",
  "a blade thrower in the wrist",
  "a flamethrower",
  "a directed force coil",
  "a liquid spray",
  "elemental magic",
  "a holy smite",
  "necrotic corruption",
  "arcane energy",
  "a terrible curse",
  "wild magic power",
  "nothing but it's build to take massive punishment",
  "nothing; it can't defend itself",
  "nothing; it can't defend itself",
  "nothing; it can't defend itself",
  "nothing; it can't defend itself",
  "nothing and it most likely will be its downfall"
  ];
   $defence = Roller($defenceD4);
//d6 The golem's condition might be described as...
$conditionD6 = [
  "pristine",
  "well-maintained",
  "showing a little wear from active duty",
  "in need of some maintenance",
  "in need of repair and soon",
  "well-maintained",
  "showing a little wear from active duty",
  "in need of some maintenance",
  "in need of repair and soon",
  "barely holding together"
  ];
   $condition = Roller($conditionD6);
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Golem | Tables</title>
  </head>
  <body>
    <h2> Random Golems </h2>
    <p>
      This is a <b><?= $mod ?></b> golem made of <b><?= $mat ?></b> that <b><?= $age ?></b> and is powered by <b><?= $power ?></b>.<br>
      <b><?= $creator ?></b> build it for <b><?= $purpose ?></b> and imbued it with <b><?= $imbued ?></b>.<br>
      The golem has <b><?= $feature ?></b>, defends itself with <b><?= $defence ?></b> and could be described as <b><?= $condition ?></b>.
    </p><br>
  </body>
</html>
